services:
  postgres:
    image: postgis/postgis:16-3.4  # Imagen que ya contiene la extension postgis
    container_name: tbd_postgres
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

volumes:
  postgres_data:
