spring.application.name=taskmanagement
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET:esta-es-la-clave-para-el-control-de-tbd-de-localizacion-geoespacial-gracias-jwt}
jwt.expiration=86400000
